// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexMart.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexMart.Migrations
{
    [DbContext(typeof(NexMartDbContext))]
    [Migration("20250118020107_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36",
                            Name = "Customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87aa8f6a-b881-43f2-8ef1-aeac782e2fb0",
                            Email = "admina@strator.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOQ4yX11i0t0fr5QPG1IPdInJn9JwWMiqvSXW9w2HQxQwioA/NphA77UwMeNQ5v5cg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "28593d9a-73f4-4034-89c7-c5b3c350527d",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d6bc2e97-e1fc-4a2f-b112-6ff861e69c37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8af89f33-a268-4f95-b545-9e7b47e61688",
                            Email = "customer1@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOOxkMHT4K29/FFi5fx8ZvoaQTrn7y4eLnRJS5G5CRxWJRzKyiAf+J/OSZvN+FYMtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ffa0820-56be-44b5-bd26-850bfae03dd6",
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = "e7cd3e98-f2cd-4b3f-c223-7ffe71f79c48",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c556f57-4e55-4dbd-9628-da9034e569f8",
                            Email = "customer2@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPaYsYECoLQZWsDLhLEkjG3SsJxbjysixWH851+OWtC9ZpLnvqf19Xe4vleFEuIG7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3317013d-a366-4a4b-baed-54ff8e93c100",
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        },
                        new
                        {
                            Id = "f8de4f99-g3de-5c4g-d334-8fff82g89d59",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fa7d9e6-9cc5-4f72-8965-c72fc02e7260",
                            Email = "customer3@company.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMXe3w5lIvXILTC+kFH1obGi3Mgua/15FRV2Uw6YiHWDBeX24bK/wcUTER/+TiDPiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb8d16b3-4385-4924-8f54-aca2b3dfaf56",
                            TwoFactorEnabled = false,
                            UserName = "customer3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "d6bc2e97-e1fc-4a2f-b112-6ff861e69c37",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        },
                        new
                        {
                            UserId = "e7cd3e98-f2cd-4b3f-c223-7ffe71f79c48",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        },
                        new
                        {
                            UserId = "f8de4f99-g3de-5c4g-d334-8fff82g89d59",
                            RoleId = "c4bbeb97-d3ba-4b53-b521-5ffa61e59b36"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NexMart.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Office Products"
                        });
                });

            modelBuilder.Entity("NexMart.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2025, 1, 7, 20, 1, 7, 616, DateTimeKind.Local).AddTicks(2778),
                            UserProfileId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2025, 1, 10, 20, 1, 7, 616, DateTimeKind.Local).AddTicks(2834),
                            UserProfileId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2025, 1, 12, 20, 1, 7, 616, DateTimeKind.Local).AddTicks(2836),
                            UserProfileId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2025, 1, 14, 20, 1, 7, 616, DateTimeKind.Local).AddTicks(2839),
                            UserProfileId = 4,
                            isCanceled = true
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2025, 1, 16, 20, 1, 7, 616, DateTimeKind.Local).AddTicks(2841),
                            UserProfileId = 3,
                            isCanceled = false
                        });
                });

            modelBuilder.Entity("NexMart.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 20,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 30,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 40,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 50,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 60,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 70,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 80,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 75,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 81,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("NexMart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest model with advanced features.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737147528/smartphone_snyc32.png",
                            Name = "Smartphone",
                            Price = 699.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High-performance laptop for work and gaming.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/laptop_rqwu1z.png",
                            Name = "Laptop",
                            Price = 999.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Noise-cancelling and long battery life.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/wirelss_earbuds_zquyxb.png",
                            Name = "Wireless Earbuds",
                            Price = 129.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Track your fitness and stay connected.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161749/smartwatch_trbw5c.png",
                            Name = "Smartwatch",
                            Price = 199.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Ultra HD display for a cinematic experience.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/4K_TV_kcravp.png",
                            Name = "4K TV",
                            Price = 499.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Next-gen console with immersive graphics.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161745/gaming_console_spdufh.png",
                            Name = "Gaming Console",
                            Price = 399.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Portable speaker with deep bass.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161740/bluetooth_speaker_mvvzdy.png",
                            Name = "Bluetooth Speaker",
                            Price = 89.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "1TB storage for backups and data.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/external_hard_drive_slcnru.png",
                            Name = "External Hard Drive",
                            Price = 59.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Capture memories in stunning detail.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161742/Digital_camera_kxhz9p.png",
                            Name = "Digital Camera",
                            Price = 349.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Lightweight tablet for on-the-go use.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737163713/tablet_fjpny0.png",
                            Name = "Tablet",
                            Price = 299.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "100% cotton and breathable.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/men_s_t-shirts_sikyul.png",
                            Name = "Men's T-Shirt",
                            Price = 19.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Comfortable and stylish fit.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/women_s_jeans_sslsjr.png",
                            Name = "Women's Jeans",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Keeps you warm in extreme cold.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/winter_jacket_fswhps.png",
                            Name = "Winter Jacket",
                            Price = 89.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Perfect for workouts or casual wear.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161750/sports_hoodie_sjqiyv.png",
                            Name = "Sports Hoodie",
                            Price = 39.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Comfortable and trendy footwear.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161749/sneakers_cibtlt.png",
                            Name = "Sneakers",
                            Price = 69.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Perfect for office or events.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161745/formal_shirt_nvaxvy.png",
                            Name = "Formal Shirt",
                            Price = 29.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Lightweight and flowy fabric.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161749/skirt_n5fkoc.png",
                            Name = "Skirt",
                            Price = 24.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Adjustable size for comfort.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161739/Baseball_cap_ekwzf6.png",
                            Name = "Baseball Cap",
                            Price = 14.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Flexible and breathable material.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/yoga_pants_ygvn9e.png",
                            Name = "Yoga Pants",
                            Price = 34.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Durable and stylish accessory.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/leather_belt_ixkvgd.png",
                            Name = "Leather Belt",
                            Price = 19.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Brew fresh coffee every morning with ease.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/coffee_maker_tm6s61.png",
                            Name = "Coffee Maker",
                            Price = 59.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Perfect for smoothies, soups, and sauces.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161739/blender_hmmby2.png",
                            Name = "Blender",
                            Price = 39.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Healthier frying with little to no oil.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/air_fryer_gtjeby.png",
                            Name = "Air Fryer",
                            Price = 89.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Durable pots and pans with nonstick coating.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161747/nonstick_cookware_set_nqdtjp.png",
                            Name = "Nonstick Cookware Set",
                            Price = 99.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Powerful suction for deep cleaning.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161750/vacuum_cleaner_vqrjio.png",
                            Name = "Vacuum Cleaner",
                            Price = 129.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Compact and efficient heating appliance.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/microwave_tiyun4.png",
                            Name = "Microwave Oven",
                            Price = 149.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Quickly boils water for tea or coffee.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/electric_kettle_oolbr4.png",
                            Name = "Electric Kettle",
                            Price = 29.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Sturdy and rust-proof drying rack.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161742/dish_rack_eswuqb.png",
                            Name = "Dish Rack",
                            Price = 19.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Cooks food faster and retains nutrients.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161748/pressure_cooker_uym9wi.png",
                            Name = "Pressure Cooker",
                            Price = 79.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "Elegant stainless steel knives and forks.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161742/cutlery_set_xlaqse.png",
                            Name = "Cutlery Set",
                            Price = 49.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "A bestselling page-turner full of suspense.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/ficiton_novel_nh0yvj.png",
                            Name = "Fiction Novel",
                            Price = 14.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Motivational tips for personal growth.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161748/self-help_guide_dttosc.png",
                            Name = "Self-Help Guide",
                            Price = 19.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "Delicious recipes for everyday cooking.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/cookbook_sfzbd5.png",
                            Name = "Cookbook",
                            Price = 24.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "An imaginative journey across galaxies.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161749/science_fiction_epic_bvvfqi.png",
                            Name = "Science Fiction Epic",
                            Price = 29.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "The life story of an influential figure.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161739/biography_ybbuyj.png",
                            Name = "Biography",
                            Price = 17.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Magic and heroism in an epic tale.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/fantasy_adventure_book_kxcpjl.png",
                            Name = "Fantasy Adventure",
                            Price = 14.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "A gripping whodunit with twists and turns.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161747/mystery_thriller_mpd5ru.png",
                            Name = "Mystery Thriller",
                            Price = 12.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Bright and engaging stories for kids.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/children_s_picture_book_ph0spz.png",
                            Name = "Children's Picture Book",
                            Price = 9.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Rich narratives set in the past.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161747/historical_fiction_book_rcjuad.png",
                            Name = "Historical Fiction",
                            Price = 19.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Beautifully written verses to inspire.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161748/poetry_collection_tqtpbu.png",
                            Name = "Poetry Collection",
                            Price = 11.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "Colorful blocks to encourage creativity.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161740/building_blocks_set_j4fmvl.png",
                            Name = "Building Blocks Set",
                            Price = 24.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Description = "A fun strategy game for the whole family.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161740/board_game_gbdxxp.png",
                            Name = "Board Game",
                            Price = 29.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "Detailed collectible for kids and adults.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/action_figure_xcdiyd.png",
                            Name = "Action Figure",
                            Price = 19.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Description = "Soft and cuddly companion for children.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161750/stuffed_animal_ro8kuy.png",
                            Name = "Stuffed Animal",
                            Price = 14.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Description = "Challenging puzzles for brain exercise.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161748/puzzle_set_w2ytxm.png",
                            Name = "Puzzle Set",
                            Price = 12.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "Fast and fun RC vehicle for kids.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161749/remote_control_car_gqev1c.png",
                            Name = "Remote Control Car",
                            Price = 39.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "Detailed dollhouse for imaginative play.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161743/dollhouse_odfmdv.png",
                            Name = "Dollhouse",
                            Price = 49.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Safe and durable swing for outdoor fun.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161747/outdoorswing_iowmjv.png",
                            Name = "Outdoor Swing",
                            Price = 59.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "Portable card game for travel or parties.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/card_game_r4rtt1.png",
                            Name = "Card Game",
                            Price = 9.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "Includes paint, brushes, and crayons.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161745/kid_s_art_kit_ekcbe8.png",
                            Name = "Kids' Art Kit",
                            Price = 19.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            Description = "Hydrates and nourishes dry skin.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/moisturizing_lotion_f1ljlf.png",
                            Name = "Moisturizing Lotion",
                            Price = 14.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            Description = "Brightens skin and reduces dark spots.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161737/vitamin_c_serum_ncuxbx.png",
                            Name = "Vitamin C Serum",
                            Price = 24.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            Description = "For soft and healthy hair.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161748/shampoo_conditioner_set_eo50m5.png",
                            Name = "Shampoo & Conditioner Set",
                            Price = 19.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            Description = "Provides a deep and thorough clean.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161743/electric_toothbrush_yd8jfw.png",
                            Name = "Electric Toothbrush",
                            Price = 29.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Description = "Includes essentials for daily makeup.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/makeup_kit_vjinoe.png",
                            Name = "Makeup Kit",
                            Price = 49.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Description = "Relax with soothing aromatherapy.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/essential_oil_diffuser_mziiyp.png",
                            Name = "Essential Oil Diffuser",
                            Price = 34.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Description = "Tracks activity, heart rate, and sleep.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161745/fitness_tracker_hfjjg4.png",
                            Name = "Fitness Tracker",
                            Price = 59.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Description = "Includes hydrating and purifying masks.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/face_mask_pack_wubexr.png",
                            Name = "Face Mask Pack",
                            Price = 12.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 7,
                            Description = "Non-slip mat for yoga and exercise.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/yoga_pants_ygvn9e.png",
                            Name = "Yoga Mat",
                            Price = 19.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 7,
                            Description = "Lightweight tent for 2 people.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161740/camping_tent_kqlfgl.png",
                            Name = "Camping Tent",
                            Price = 89.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            Description = "Durable backpack with multiple compartments.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/hiking_backpack_jznpao.png",
                            Name = "Hiking Backpack",
                            Price = 49.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            Description = "Telescopic fishing rod for outdoor adventures.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161744/fishing_rod_nbipzz.png",
                            Name = "Fishing Rod",
                            Price = 39.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 7,
                            Description = "Official size and weight basketball.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161739/basketball_a6xgmd.png",
                            Name = "Basketball",
                            Price = 29.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            Description = "Warm and lightweight sleeping bag.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161749/sleeping_bag_mckumk.png",
                            Name = "Sleeping Bag",
                            Price = 34.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 7,
                            Description = "Insulated bottle to keep drinks hot or cold.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161737/water_bottle_c5ryy9.png",
                            Name = "Water Bottle",
                            Price = 14.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 7,
                            Description = "Adjustable weights for strength training.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161743/dumbbell_set_ksagsb.png",
                            Name = "Dumbbell Set",
                            Price = 59.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 7,
                            Description = "Protective helmet for cycling.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161739/bicycle_helmet_amk6no.png",
                            Name = "Bicycle Helmet",
                            Price = 39.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 7,
                            Description = "Lightweight poles for hiking.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161750/trekking_poles_pvlbje.png",
                            Name = "Trekking Poles",
                            Price = 24.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 8,
                            Description = "Includes sponge, soap, and microfiber towel.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/car_wash_kit_l6rmsa.png",
                            Name = "Car Wash Kit",
                            Price = 29.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 8,
                            Description = "Portable vacuum for interior cleaning.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/car_vauum_cleaner_aazhcv.png",
                            Name = "Car Vacuum Cleaner",
                            Price = 49.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            Description = "Energy-efficient and bright LED headlights.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161746/LED_headlights_jhsqst.png",
                            Name = "LED Headlights",
                            Price = 79.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            Description = "Compact and easy-to-use air compressor.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161750/tire_inflator_ntu5jp.png",
                            Name = "Tire Inflator",
                            Price = 39.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 8,
                            Description = "Records high-definition video for safety.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161742/dashboard_camera_bp3aff.png",
                            Name = "Dashboard Camera",
                            Price = 99.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 8,
                            Description = "Stylish and durable covers for car seats.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/car_seat_cover_set_c6h5wo.png",
                            Name = "Car Seat Cover Set",
                            Price = 59.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 9,
                            Description = "Durable chew toy for dogs of all sizes.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161742/dog_chew_toy_wa5vcl.png",
                            Name = "Dog Chew Toy",
                            Price = 9.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 9,
                            Description = "Sturdy post to keep your cat entertained.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161741/cat_scratching_post_if1syl.png",
                            Name = "Cat Scratching Post",
                            Price = 24.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 9,
                            Description = "Non-slip bowl for feeding your pets.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161747/pet_food_bowl_tyhbdu.png",
                            Name = "Pet Food Bowl",
                            Price = 7.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            Description = "Complete kit for setting up a home aquarium.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161739/aquarium_starter_kit_vqzhea.png",
                            Name = "Aquarium Starter Kit",
                            Price = 49.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 9,
                            Description = "Strong and adjustable leash for dogs.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161743/dog_leash_ywpqez.png",
                            Name = "Dog Leash",
                            Price = 14.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 10,
                            Description = "Comfortable and adjustable chair for office use.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161743/ergonomic_office_chair_klsqqj.png",
                            Name = "Ergonomic Office Chair",
                            Price = 149.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 10,
                            Description = "Compact and responsive keyboard-mouse combo.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161738/wireless_keyboard_and_mouse_sdrcu3.png",
                            Name = "Wireless Keyboard and Mouse",
                            Price = 39.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 10,
                            Description = "Keeps your desk neat and clutter-free.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161742/desk_organizer_jrdpch.png",
                            Name = "Desk Organizer",
                            Price = 19.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 10,
                            Description = "Set of 3 notebooks for work or study.",
                            ImageUrl = "https://res.cloudinary.com/dpq83a6ds/image/upload/v1737161747/notebook_set_fw4axu.png",
                            Name = "Notebook Set",
                            Price = 12.99m,
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("NexMart.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            Address = " 220 High Street",
                            FirstName = "Tom",
                            IdentityUserId = "d6bc2e97-e1fc-4a2f-b112-6ff861e69c37",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 3,
                            Address = "300 Elm Avenue",
                            FirstName = "Jane",
                            IdentityUserId = "e7cd3e98-f2cd-4b3f-c223-7ffe71f79c48",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            Address = "400 Oak Street",
                            FirstName = "John",
                            IdentityUserId = "f8de4f99-g3de-5c4g-d334-8fff82g89d59",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexMart.Models.Order", b =>
                {
                    b.HasOne("NexMart.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("NexMart.Models.OrderProduct", b =>
                {
                    b.HasOne("NexMart.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexMart.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NexMart.Models.Product", b =>
                {
                    b.HasOne("NexMart.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NexMart.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("NexMart.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
